/** Copyright 2018 He Hao<hehaoslj@sina.com> */

//! this file is generated by script

#ifndef FUTUREMODEL_INCLUDE_VARIANTFEATURE_H_
#define FUTUREMODEL_INCLUDE_VARIANTFEATURE_H_

#endif  // FUTUREMODEL_INCLUDE_VARIANTFEATURE_H_
